services:
  poker-dice-postgres:
    container_name: poker-dice-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d

  poker-dice-jvm-static:
    container_name: poker-dice-jvm-static
    hostname: poker-dice-jvm-static
    build:
      context: ..
      dockerfile: SQL/docker/Dockerfile-jvm
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://poker-dice-postgres:5432/db?user=dbuser&password=changeit
    ports:
      - 8080:8080
    depends_on:
      - poker-dice-postgres

  poker-dice-jvm-dynamic:
    container_name: poker-dice-jvm-dynamic
    hostname: poker-dice-jvm-dynamic
    build:
      context: ..
      dockerfile: SQL/docker/Dockerfile-jvm
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://poker-dice-postgres:5432/db?user=dbuser&password=changeit
    ports:
      - 8088:8080
    depends_on:
      - poker-dice-postgres

  nginx:
    container_name: poker-dice-nginx
    build:
      context: ..
      dockerfile: SQL/docker/Dockerfile-nginx
    ports:
      - 3000:3000
      - 3001:3001
      - 4000:4000
    depends_on:
      - poker-dice-jvm-static
      - poker-dice-jvm-dynamic
